server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/webflux_security
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/webflux_security
    user: postgres
    password: postgres
    locations: classpath:db/migration

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 54
      keyLength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: wertyxa